web-pos-team1/web-pos-team1-be

src/main/java/com/ssg/webpos/config/SecurityConfig.java, src/main/java/com/ssg/webpos/domain/BranchAdmin.java, src/main/java/com/ssg/webpos/domain/Coupon.java, src/main/java/com/ssg/webpos/domain/Delivery.java, src/main/java/com/ssg/webpos/domain/DeliveryAddress.java, src/main/java/com/ssg/webpos/domain/Event.java, src/main/java/com/ssg/webpos/domain/HQAdmin.java, src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/domain/OrderProduct.java, src/main/java/com/ssg/webpos/domain/PointHistory.java, src/main/java/com/ssg/webpos/domain/Pos.java, src/main/java/com/ssg/webpos/domain/Product.java, src/main/java/com/ssg/webpos/domain/ProductRequest.java, src/main/java/com/ssg/webpos/domain/SettlementDay.java, src/main/java/com/ssg/webpos/domain/SettlementMonth.java, src/main/java/com/ssg/webpos/domain/StockReport.java, src/main/java/com/ssg/webpos/domain/Store.java, src/main/java/com/ssg/webpos/domain/User.java, src/main/resources/application.yml
=> fix: 연관관계설정

src/main/java/com/ssg/webpos/controller/UserController.java
UserController 파일 추가 후 사용자 전체 조회 기능을 위해 getUserList라는 메서드를 생성했습니다.
=> feat: 사용자 전체 조회 메서드 생성

src/main/java/com/ssg/webpos/domain/BranchAdmin.java, src/main/java/com/ssg/webpos/domain/Coupon.java, src/main/java/com/ssg/webpos/domain/Delivery.java, src/main/java/com/ssg/webpos/domain/DeliveryAddress.java, src/main/java/com/ssg/webpos/domain/Event.java, src/main/java/com/ssg/webpos/domain/HQAdmin.java, src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/domain/OrderProduct.java, src/main/java/com/ssg/webpos/domain/PointHistory.java, src/main/java/com/ssg/webpos/domain/Pos.java, src/main/java/com/ssg/webpos/domain/Product.java, src/main/java/com/ssg/webpos/domain/ProductRequest.java, src/main/java/com/ssg/webpos/domain/SettlementDay.java, src/main/java/com/ssg/webpos/domain/SettlementMonth.java, src/main/java/com/ssg/webpos/domain/StockReport.java, src/main/java/com/ssg/webpos/domain/Store.java
JpaRepository에서 제공하는 메서드 사용하기위해 기본생성자 추가
=> chore: 정산테이블 생성일자 컬럼 추가 및 기본생성자 추가

src/main/java/com/ssg/webpos/domain/Cart.java, src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/repository/cart/CartRepository.java, src/main/java/com/ssg/webpos/service/CartService.java, src/test/java/com/ssg/webpos/service/CartServiceTest.java
CartService에서 장바구니에 담긴 상품 삭제 기능(delCart) 구현,
장바구니 상품 삭제 후 minusTotalPrice 메서드를 활용한 totalPrice 감소 테스트 코드 작성
=> feat : 장바구니 삭제 기능 구현, 테스트 코드 작성

src/main/java/com/ssg/webpos/domain/Cart.java, src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/dto/CartAddDTO.java, src/main/java/com/ssg/webpos/dto/OrderDTO.java, src/main/java/com/ssg/webpos/repository/cart/CartRepository.java, src/main/java/com/ssg/webpos/repository/order/OrderRepository.java, src/main/java/com/ssg/webpos/service/CartService.java, src/test/java/com/ssg/webpos/service/CartServiceTest.java
CartService에서 주문 생성 후 장바구니 상품 담기 기능 (addOrder) 구현,
cartAddDTOList에 장바구니 상품 리스트를 추가하고 주문 저장하여 테스트
=> feat : 주문 생성 후 장바구니 상품 담기 기능 구현 및 테스트

src/main/java/com/ssg/webpos/domain/Cart.java, src/main/java/com/ssg/webpos/domain/Product.java, src/main/java/com/ssg/webpos/service/CartService.java, src/test/java/com/ssg/webpos/service/CartServiceTest.java
CartService에서 주문 취소 기능(cancelOrder) 구현,
주문 취소 후 OrderStatus.CANCEL로 상태 변경 및 plusStockQuantity 메서드를 활용한 재고 수량 증가 테스트 코드 작성
=> feat : 주문 취소 기능 구현 및 테스트 코드 작성

src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/repository/CartRedisImplRepository.java, src/main/java/com/ssg/webpos/service/CartService.java, src/test/java/com/ssg/webpos/repository/CartRedisRepositoryTest.java, src/test/java/com/ssg/webpos/service/CartServiceTest.java
CartService에서 장바구니에 중복 상품을 담았을 경우 수량만 증가시키도록 코드 개선(addOrder), 
minusStockQuantity 메서드를 활용하여 주문 시 재고 감소 시킴
=> refactor : 장바구니에 중복 상품 담기 기능 개선

src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/dto/OrderDTO.java, src/main/java/com/ssg/webpos/service/CartService.java, src/test/java/com/ssg/webpos/service/CartServiceTest.java
도메인 Order에 serialNumber 컬럼 추가, 
CartService의 addOrder 메서드에 '주문 날짜와 주문 Id'를 조합하여 unique한 주문 일련 번호 생성 코드 작성
=> feat : 주문 일련번호 추가

src/main/java/com/ssg/webpos/controller/DeliveryController.java, src/main/java/com/ssg/webpos/domain/Delivery.java, src/main/java/com/ssg/webpos/dto/DeliveryDTO.java, src/main/java/com/ssg/webpos/repository/DeliveryRepository.java, src/main/java/com/ssg/webpos/repository/delivery/DeliveryRedisImplRepository.java, src/main/java/com/ssg/webpos/repository/delivery/DeliveryRedisRepository.java, src/main/java/com/ssg/webpos/repository/delivery/DeliveryRepository.java, src/main/java/com/ssg/webpos/service/DeliveryService.java, src/test/java/com/ssg/webpos/repository/DeliveryRedisRepositoryTest.java, src/test/java/com/ssg/webpos/service/CartServiceTest.java, src/test/java/com/ssg/webpos/service/DeliveryServiceTest.java
deliveryService에 배송지 정보 추가 기능(addDeliveryAddress) 및  redis 캐싱 저장 기능(DeliveryRedisImplRepository) 구현,
redis 캐싱 저장된 배송지 정보 리스트를 PosStoreCompositeId 조합키로 가져오는 테스트 코드 작성
=> feat : 배송지 정보 redis 캐싱 기능 구현 및 테스트 코드 작성

src/main/java/com/ssg/webpos/config/SecurityConfig.java, src/main/java/com/ssg/webpos/config/WebConfig.java, src/main/java/com/ssg/webpos/config/auth/PrincipalDetails.java, src/main/java/com/ssg/webpos/config/auth/PrincipalDetailsService.java, src/main/java/com/ssg/webpos/controller/HelloController.java, src/main/java/com/ssg/webpos/controller/ProductController.java, src/main/java/com/ssg/webpos/domain/Product.java, src/main/java/com/ssg/webpos/dto/ProductListResponseDTO.java, src/main/java/com/ssg/webpos/repository/BranchAdminRepository.java, src/main/java/com/ssg/webpos/repository/HQAdminRepository.java, src/main/java/com/ssg/webpos/repository/product/ProductRepository.java, src/main/java/com/ssg/webpos/service/ProductService.java
+ `ProductController`에서 `[GET] | /api/v1/products/{category}` 요청 들어올 경우 JPA 쿼리메서드를 사용해서 productRepository.findByCategory(category)를 통해 {category}에 해당하는 상품리스트를 ResponseEntity.body()에 담아서 return
+ 관리자 로그인을 위해 UserService를 implements 한 PrincipalDetails 클래스 작성
=> feat: 상품 전체 리스트 조회 기능구현 및 security 설정

src/main/java/com/ssg/webpos/controller/CartController.java, src/main/java/com/ssg/webpos/controller/PointController.java, src/main/java/com/ssg/webpos/dto/PointDTO.java, src/main/java/com/ssg/webpos/repository/CartRedisImplRepository.java, src/test/java/com/ssg/webpos/repository/CartRedisRepositoryTest.java
CartRedisImplrepository savePoint
- phoneNumber로 user DB에 저장되어있는 userId redis 저장
=> feat: redis userId 저장

src/main/java/com/ssg/webpos/controller/DeliveryController.java, src/main/java/com/ssg/webpos/domain/DeliveryAddress.java, src/main/java/com/ssg/webpos/domain/User.java, src/main/java/com/ssg/webpos/dto/DeliveryAddressListDTO.java, src/main/java/com/ssg/webpos/repository/UserRepository.java, src/main/java/com/ssg/webpos/repository/delivery/DeliveryAddressRepository.java, src/main/java/com/ssg/webpos/repository/delivery/DeliveryRedisImplRepository.java, src/main/java/com/ssg/webpos/repository/delivery/DeliveryRedisRepository.java, src/main/java/com/ssg/webpos/service/DeliveryService.java, src/test/java/com/ssg/webpos/service/DeliveryServiceTest.java
+ 포인트 redis에 캐싱되어 있는 userId를 찾아옴(DeliveryRedisImplRepository)  
+ 찾은 userId로 user 정보를 가져와서 delivery_list 테이블에 저장된 해당 유저의 배송지 목록을 조회하는 기능 구현(DeliveryService)
=> feat: 회원 배송지 목록 조회 기능 구현

src/main/java/com/ssg/webpos/controller/PaymentsApiController.java, src/main/java/com/ssg/webpos/controller/PointController.java, src/main/java/com/ssg/webpos/dto/PaymentsDTO.java, src/main/java/com/ssg/webpos/dto/PointDTO.java, src/main/java/com/ssg/webpos/repository/CartRedisImplRepository.java, src/main/java/com/ssg/webpos/repository/CartRedisRepository.java, src/main/java/com/ssg/webpos/service/CartRedisService.java, src/main/java/com/ssg/webpos/service/PaymentsService.java, src/main/java/com/ssg/webpos/service/PointService.java, src/main/java/com/ssg/webpos/service/UserService.java, src/main/resources/templates/welcome.html, src/test/java/com/ssg/webpos/repository/CartRedisRepositoryTest.java, src/test/java/com/ssg/webpos/service/CartRedisServiceTest.java, src/test/java/com/ssg/webpos/service/CartServiceTest.java
결제 후 orderDB, cartDB에 redis 데이터를 저장.
결제 한 redis 데이터는 삭제됨.
=> feat: redis 데이터를 orderDB, cartDB 테이블에 저장 및 로직 수정

src/main/java/com/ssg/webpos/controller/CouponController.java, src/main/java/com/ssg/webpos/controller/PaymentsApiController.java, src/main/java/com/ssg/webpos/controller/PointController.java, src/main/java/com/ssg/webpos/domain/DeliveryAddress.java, src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/domain/PointSaveHistory.java, src/main/java/com/ssg/webpos/domain/PointUseHistory.java, src/main/java/com/ssg/webpos/domain/User.java, src/main/java/com/ssg/webpos/dto/PaymentsDTO.java, src/main/java/com/ssg/webpos/dto/PointUseDTO.java, src/main/java/com/ssg/webpos/repository/PointUseHistoryRepository.java, src/main/java/com/ssg/webpos/repository/UserRepository.java, src/main/java/com/ssg/webpos/repository/cart/CartRedisImplRepository.java, src/main/java/com/ssg/webpos/repository/cart/CartRedisRepository.java, src/main/java/com/ssg/webpos/service/CouponService.java, src/main/java/com/ssg/webpos/service/PaymentsService.java, src/main/java/com/ssg/webpos/service/PointHistoryService.java, src/main/java/com/ssg/webpos/service/PointService.java, src/main/resources/templates/welcome.html, src/test/java/com/ssg/webpos/repository/CartRedisRepositoryTest.java, src/test/java/com/ssg/webpos/service/CouponServiceTest.java, src/test/java/com/ssg/webpos/service/PaymentsServiceTest.java, src/test/java/com/ssg/webpos/service/PointHistoryServiceTest.java, src/test/java/com/ssg/webpos/service/PointServiceTest.java
1. 포인트 차감 기능
- pointService 
- deductPoints
2. 포인트 차감 기능 테스트
- 포인트 차감 성공
- 포인트 차감 실패: 포인트 부족
=> feat: 포인트 사용 amount 캐싱 기능,  point 차감 기능 구현 및 테스트 코드 작성

.gitignore, build.gradle, src/main/java/com/ssg/webpos/controller/ProductController.java, src/main/java/com/ssg/webpos/dto/ProductListResponseDTO.java, src/main/java/com/ssg/webpos/repository/product/ProductRepository.java, src/main/java/com/ssg/webpos/service/ProductService.java, src/main/resources/application.yml
+ 현재는 이벤트 상품 조회할 때, ProductService의 `findByCategory()` , `findByCategoryWithEvent()` 두 개의 메서드로 쿼리를 보내서 모두 불러옴
+ 이후 ArrayList 연산을 통해서 필터링 로직을 수행함
+ **추후 쿼리 및 ERD 수정과 로직 수정 필요**
=> feat: 카테고리 별 상품 조회 기능 구현

src/main/java/com/ssg/webpos/controller/DeliveryController.java, src/main/java/com/ssg/webpos/controller/GiftController.java, src/main/java/com/ssg/webpos/domain/Delivery.java, src/main/java/com/ssg/webpos/dto/GiftRequestDTO.java, src/main/java/com/ssg/webpos/dto/delivery/DeliveryAddDTO.java, src/main/java/com/ssg/webpos/dto/delivery/DeliveryRequestDTO.java, src/main/java/com/ssg/webpos/dto/delivery/RequestDeliveryTimeDTO.java, src/main/java/com/ssg/webpos/repository/delivery/DeliveryRedisImplRepository.java, src/main/java/com/ssg/webpos/service/DeliveryService.java, src/main/resources/application.properties, src/test/java/com/ssg/webpos/repository/DeliveryRedisRepositoryTest.java, src/test/java/com/ssg/webpos/service/DeliveryServiceTest.java
+ delivery 엔티티에서 배송 요청 시간(requestDeliveryTime) 타입을 LocalDateTime에서 String으로 변경
+ DeliveryRedisImplRepository에서 GiftRequestDTO를 redis 캐싱하는 메서드 구현(saveGiftRecipientInfo)
+ GiftRequestDTO를 입력하여 saveGiftRecipientInfo 메서드 테스트 코드 작성
=> feat: 선물하기 redis 캐싱 기능 구현 및 테스트

build.gradle, src/main/java/com/ssg/webpos/config/RedisConfig.java, src/main/resources/application.properties
+ docker logs {container_id}를 통해 로그를 살펴본 결과 해킹을 받았던 기록을 발견함.
+ redis-cli에서 team1이라는 사용자를 생성하고 password를 적용시킴으로 써 보안적으로 강화시켰음.
+ 이를 redisTemplate 설정에도 반영함.
@yhk313 님과 함께 에러 해결함
=> fix: redis 자동삭제되는 문제 해결

src/main/java/com/ssg/webpos/domain/PointSaveHistory.java, src/main/java/com/ssg/webpos/domain/PointUseHistory.java, src/main/java/com/ssg/webpos/dto/CartAddDTO.java, src/main/java/com/ssg/webpos/service/PaymentsService.java, src/test/java/com/ssg/webpos/service/PaymentsServiceTest.java
updateProductStock
- 결제 완료 시 cart 테이블에 저장하고 product테이블의 재고를 업데이트한다.
=> chore: Cart 엔티티를 저장하고 상품 재고를 업데이트하는 코드 수정

src/main/java/com/ssg/webpos/controller/SmsController.java, src/main/java/com/ssg/webpos/controller/admin/BranchAdminManagerController.java, src/main/java/com/ssg/webpos/domain/Cart.java, src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/domain/Point.java, src/main/java/com/ssg/webpos/domain/PointSaveHistory.java, src/main/java/com/ssg/webpos/domain/PointUseHistory.java, src/main/java/com/ssg/webpos/domain/User.java, src/main/java/com/ssg/webpos/domain/enums/PayMethod.java, src/main/java/com/ssg/webpos/repository/PointRepository.java, src/main/java/com/ssg/webpos/service/CartService.java, src/main/java/com/ssg/webpos/service/PaymentsService.java, src/main/java/com/ssg/webpos/service/PointService.java, src/test/java/com/ssg/webpos/repository/CartRedisRepositoryTest.java, src/test/java/com/ssg/webpos/repository/PointUseHistoryRepositoryTest.java, src/test/java/com/ssg/webpos/repository/UserRepositoryTest.java, src/test/java/com/ssg/webpos/service/CartServiceTest.java, src/test/java/com/ssg/webpos/service/DeliveryServiceTest.java, src/test/java/com/ssg/webpos/service/PaymentsServiceTest.java, src/test/java/com/ssg/webpos/service/PointServiceTest.java, src/test/java/com/ssg/webpos/service/PointUseHistoryServiceTest.java
- Point 엔티티 추가
- PointUseHistory, PointSaveHisory 엔티티 필드, 연관 관계 수정
=> chore: Point 엔티티 추가, 엔티티 필드 수정 및 코드 수정

src/main/java/com/ssg/webpos/domain/SettlementDay.java, src/main/java/com/ssg/webpos/domain/Store.java
+ SettlementDay : extends Basetime 삭제
+ SettlementMonth : extends Basetime 삭제
+ Store : postCode 타입을 int에서 String으로 변경
=> fix : SettlementDay,SettlementMonth,Store

src/main/java/com/ssg/webpos/domain/Product.java
=> fix:Product

src/main/java/com/ssg/webpos/controller/PointController.java, src/main/java/com/ssg/webpos/domain/BaseTime.java, src/main/java/com/ssg/webpos/domain/Point.java, src/main/java/com/ssg/webpos/domain/PointSaveHistory.java, src/main/java/com/ssg/webpos/domain/PointUseHistory.java, src/main/java/com/ssg/webpos/dto/PaymentsDTO.java, src/main/java/com/ssg/webpos/dto/point/PointUseRequestDTO.java, src/main/java/com/ssg/webpos/dto/point/PointUseResponseDTO.java, src/main/java/com/ssg/webpos/repository/PointSaveHistoryRepository.java, src/main/java/com/ssg/webpos/repository/cart/CartRedisImplRepository.java, src/main/java/com/ssg/webpos/repository/cart/CartRedisRepository.java, src/main/java/com/ssg/webpos/service/PaymentsService.java, src/main/java/com/ssg/webpos/service/PointSaveHistoryService.java, src/main/java/com/ssg/webpos/service/PointService.java, src/test/java/com/ssg/webpos/repository/CartRedisRepositoryTest.java, src/test/java/com/ssg/webpos/service/PaymentsServiceTest.java, src/test/java/com/ssg/webpos/service/PointUseHistoryServiceTest.java
주문번호 수정
- 년월일 + storeId + posId + orderId (ex. 20230530+ 01 + 01 + 0001)
=> chore: 주문번호 및 point 적립/사용 로직 수정

src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/dto/hqStock/StockReportResponseDTO.java, src/main/java/com/ssg/webpos/repository/StockReportRepository.java, src/main/java/com/ssg/webpos/repository/order/OrderRepository.java, src/main/java/com/ssg/webpos/service/hqController/method/HqControllerStockService.java, src/test/java/com/ssg/webpos/repository/OrderRepositoryTest.java
+ 전체, store_id별, 판매 여부 재고 조회
+ 재고내역 DTO 생성
=> feat : HQ stockManage

src/main/java/com/ssg/webpos/controller/admin/BranchAdminManagerController.java, src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/dto/hqStock/StockReportResponseDTO.java, src/main/java/com/ssg/webpos/dto/hqStock/StockReportUpdateRequestDTO.java, src/main/java/com/ssg/webpos/dto/order/OrderDetailProductResponseDTO.java, src/main/java/com/ssg/webpos/dto/order/OrderDetailResponseDTO.java, src/main/java/com/ssg/webpos/repository/StockReportRepository.java, src/main/java/com/ssg/webpos/repository/product/ProductRepository.java, src/main/java/com/ssg/webpos/service/hqController/method/HqControllerStockService.java, src/main/java/com/ssg/webpos/service/hqController/method/StockReportUpdateService.java, src/test/java/com/ssg/webpos/repository/ProductRepositoryTest.java, src/test/java/com/ssg/webpos/repository/StockReportRepositoryTest.java
+ 재고 관리 페이지에서 재고수량, 판매가, 원가 ASC, DESC 순 정렬하는 기능 구현
+ 판매 여부에 따른 조회 구현
+ store_id에 따른 조회, 전체 조회 구현
+ 복합적인 조회 구현
+ 재고 내역 수정 기능 구현
=> feat : HqAdminController stock,salePrice,originPrice ASC/DESC, stock modify

src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/domain/language/CN.java, src/main/java/com/ssg/webpos/domain/language/EN.java, src/main/java/com/ssg/webpos/domain/language/JA.java, src/main/java/com/ssg/webpos/domain/language/KO.java, src/main/java/com/ssg/webpos/dto/hqSale/HqSettlementDayDTO.java, src/main/java/com/ssg/webpos/repository/order/OrderRepository.java, src/main/java/com/ssg/webpos/repository/settlement/SettlementDayRepository.java, src/main/java/com/ssg/webpos/service/hqController/method/SettlementDayByTermService.java, src/test/java/com/ssg/webpos/repository/SettlementReeositoryTest.java
=> feat : 언어별 도메인 추가

src/main/java/com/ssg/webpos/domain/language/CN.java, src/main/java/com/ssg/webpos/domain/language/EN.java, src/main/java/com/ssg/webpos/domain/language/JA.java, src/main/java/com/ssg/webpos/domain/language/KO.java
=> fix : 언어 도메인 수정

src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/dto/ReissueTokenResponseDTO.java, src/main/java/com/ssg/webpos/service/HQAdminService.java
- HqAdminController의 reissue() 메서드를 통해 refresh token이 만료되지 않았을 때, access token을 새롭게 발행해주는 기능 구현
=> feat: JWT 재발행 기능 구현

src/main/java/com/ssg/webpos/controller/admin/BranchAdminManagerController.java, src/main/java/com/ssg/webpos/dto/order/OrderDetailResponseDTO.java
orderDetailResponseDTO 필드
+ 가게의 이름, 주소 필드 추가
+ 회원의 이름,소유 포인트 필드 추가(비회원인 경우 이름은 " ", 소유 포인트는 0)
+ 과세물품가액, 부가세 필드 추가
+ 컨트롤러에서 DTO 활용 매서드 생성
=> feat:modify orderDetailResponseDTO

build.gradle, src/main/java/com/ssg/webpos/config/SwaggerConfig.java, src/main/java/com/ssg/webpos/controller/DeliveryController.java, src/main/java/com/ssg/webpos/controller/OrderController.java, src/main/java/com/ssg/webpos/dto/delivery/DeliveryAddDTO.java, src/main/java/com/ssg/webpos/dto/delivery/DeliveryRedisAddRequestDTO.java, src/main/java/com/ssg/webpos/repository/order/OrderRepository.java, src/main/java/com/ssg/webpos/service/CartService.java, src/main/resources/application.yml, src/test/java/com/ssg/webpos/service/CartServiceTest.java
- swagger ui 적용(`build.gradle`, `SwaggerConfig` 설정)
- DeliveryController의 'getDeliveryInfo', 'addDeliveryInfo' 메서드와 'DeliveryRedisAddRequestDTO'에 swagger 어노테이션 적용
- CartService에서 'cancelOrder' 로직 변경
- 주문 취소하는 order 객체를 'merchantUid'로 찾아오는 로직으로 변경
=> docs: swagger ui 적용 및 사용 방법 문서화

src/main/java/com/ssg/webpos/controller/admin/BranchAdminManagerController.java, src/main/java/com/ssg/webpos/dto/order/OrderDetailResponseDTO.java, src/main/java/com/ssg/webpos/repository/order/OrderRepository.java, src/test/java/com/ssg/webpos/repository/OrderRepositoryTest.java
+ 주문 취소 날짜, 전화번호, 대표자명, 사업자번호, serialNumber 추가
+ POSTMAN 확인 완료
=> chore : 주문 취소 영수증 컨트롤러 수정

src/main/java/com/ssg/webpos/controller/admin/BranchAdminManagerController.java, src/main/java/com/ssg/webpos/domain/Order.java, src/main/java/com/ssg/webpos/dto/order/OrderDetailResponseDTO.java, src/main/java/com/ssg/webpos/service/CartService.java, src/main/java/com/ssg/webpos/service/SmsService.java
orderDetailResponseDTO에 pointSaveAmount 필드 추가 및 코드 수정
=> chore: 주문 영수증 controller 수정

src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/dto/hqSale/HqListForSaleDTO.java, src/main/java/com/ssg/webpos/repository/order/OrderRepository.java, src/main/java/com/ssg/webpos/repository/settlement/SettlementDayRepository.java, src/main/java/com/ssg/webpos/service/hqController/csv/CsvService.java, src/main/java/com/ssg/webpos/service/hqController/method/SaleMethodService.java, src/test/java/com/ssg/webpos/repository/SettlementReeositoryTest.java, src/test/java/com/ssg/webpos/service/settlement/SettlementDayTest.java
+ orders 활용에서 settlement_day 활용으로 변경
+ 매서드, 레포지토리, 컨트롤러 변경
+ 매출 관련 DTO csv 변환 서비스 생성
=> feat : sale by settlement_day

node_modules/.yarn-integrity, src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/repository/settlement/SettlementDayRepository.java
+ store_id별 매출목록 조회 및 csv 저장 기능 구현(settlement_day 활용)
+ csv 저장 경로 지정할 때 사용자 정보 활용
+ webpos라는 폴더가 없다면 새로 만드는 기능 구현
=> feat : store_id별 매출목록 조회, csv 저장 경로 구현

build.gradle, src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/controller/admin/TestForCSVController.java
=> feat : add ordeList

src/main/java/com/ssg/webpos/controller/admin/BranchAdminManagerController.java, src/main/java/com/ssg/webpos/dto/StoreName.java
=> chore: 가게 이름 API

src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/dto/hqSale/HqSaleOrderDTO.java, src/main/java/com/ssg/webpos/repository/order/OrderRepository.java, src/main/java/com/ssg/webpos/service/hqController/csv/CsvService.java, src/main/java/com/ssg/webpos/service/hqController/method/SaleMethodService.java
+ DTO에서 serialNumber 필드 삭제, merchantUid 필드 추가
+ Controller에서 날짜 DESC순 정렬
=> chore : 주문목록 조회 수정

build.gradle, src/main/java/com/ssg/webpos/controller/admin/BranchAdminManagerController.java, src/main/java/com/ssg/webpos/controller/admin/HqAdminController.java, src/main/java/com/ssg/webpos/dto/StoreName.java, src/main/java/com/ssg/webpos/service/hqController/csv/CsvService.java
- currently can save `csv` file on Windows OS
- can get userName from `System.getProperty()` method to argument `user.name`
=> fix: FileNotFoundException by using System.getProperty()
